#release configuration
#Mon Mar 02 16:51:59 PST 2026
completedPhase=run-preparation-goals
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.coen6761\:robotmotion=1.1-SNAPSHOT
project.rel.coen6761\:robotmotion=1.0
project.scm.coen6761\:robotmotion.connection=scm\:git\:https\://github.com/SalmaAl22/RobotMotion.git
project.scm.coen6761\:robotmotion.developerConnection=scm\:git\:https\://github.com/SalmaAl22/RobotMotion.git
project.scm.coen6761\:robotmotion.tag=HEAD
project.scm.coen6761\:robotmotion.url=https\://github.com/SalmaAl22/RobotMotion
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=robotmotion-1.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:ssh\://git@github.com/SalmaAl22/RobotMotion.git
